"""add unique constraint user_course on enrollments

Revision ID: 7b9fe59be1a4
Revises: 0010
Create Date: 2026-03-12 19:08:25.202807

"""
from collections.abc import Sequence

from alembic import op


# revision identifiers, used by Alembic.
revision: str = '7b9fe59be1a4'
down_revision: str | Sequence[str] | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_enrollments_user_course', 'enrollments', ['user_id', 'course_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_enrollments_user_course', 'enrollments', type_='unique')
    # ### end Alembic commands ###
