"""move passing_score max_attempts to modules remove is_mandatory from courses

Revision ID: b9c388c1420a
Revises: 8421642c0b49
Create Date: 2026-03-12 21:10:22.678887

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'b9c388c1420a'
down_revision: str | Sequence[str] | None = '8421642c0b49'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add new columns with server_default so existing rows get values.
    op.add_column(
        'course_modules',
        sa.Column('passing_score', sa.Integer(), nullable=False, server_default=sa.text('80')),
    )
    op.add_column(
        'course_modules',
        sa.Column('max_attempts', sa.Integer(), nullable=False, server_default=sa.text('3')),
    )

    # Copy course-level values into each module.
    op.execute(
        """
        UPDATE course_modules m
        SET passing_score = c.passing_score,
            max_attempts  = c.max_attempts
        FROM courses c
        WHERE m.course_id = c.id
        """
    )

    # Remove server_default — app controls the value from now on.
    op.alter_column('course_modules', 'passing_score', server_default=None)
    op.alter_column('course_modules', 'max_attempts', server_default=None)

    # Drop moved / removed columns from courses.
    op.drop_column('courses', 'is_mandatory')
    op.drop_column('courses', 'max_attempts')
    op.drop_column('courses', 'passing_score')


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('passing_score', sa.INTEGER(), server_default=sa.text('80'), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('max_attempts', sa.INTEGER(), server_default=sa.text('3'), autoincrement=False, nullable=False))
    op.add_column('courses', sa.Column('is_mandatory', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.drop_column('course_modules', 'max_attempts')
    op.drop_column('course_modules', 'passing_score')
    # ### end Alembic commands ###
