"""remove company_id add enrollment_id to access codes

Revision ID: ecd75ab8397e
Revises: b17ef02b7985
Create Date: 2026-03-12 20:25:59.530258

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ecd75ab8397e'
down_revision: str | Sequence[str] | None = 'b17ef02b7985'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_codes', sa.Column('enrollment_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_index(op.f('ix_access_codes_enrollment_id'), 'access_codes', ['enrollment_id'], unique=False)
    op.drop_column('access_codes', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('access_codes', sa.Column('company_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_access_codes_enrollment_id'), table_name='access_codes')
    op.drop_column('access_codes', 'enrollment_id')
    # ### end Alembic commands ###
