"""Certificate domain entity."""

from datetime import UTC, datetime

from pydantic import BaseModel

from app.shared.entities.audit_entity import AuditEntity

from ..enums import CertificateStatus


class CertificateData(BaseModel):
    """Input model for creating a certificate.

    Contains only the caller-provided business fields. Generated fields
    (token) and output-only state fields (revocation) live on the entity.
    Used as the data transfer object between the presentation and
    application layers.

    Attributes:
        company_id: Tenant that issued the certificate.
        recipient_id: User who received the certificate.
        title: Human-readable name of the certificate.
        description: Optional longer description of the certification.
        issued_at: Timestamp when the certificate was officially issued.
        expires_at: Optional expiration timestamp.
    """

    company_id: str
    recipient_id: str
    title: str
    description: str | None = None
    issued_at: datetime | None = None
    expires_at: datetime | None = None


class CertificateEntity(CertificateData, AuditEntity):
    """Represents a digital certificate issued to a user.

    Full domain entity that combines business fields with audit metadata
    and adds generated / output-only fields. Returned by the repository
    after persistence.

    Attributes:
        token: Unique ULID token embedded in the QR code. Generated by
            IssueCertificateUseCase — never provided by the caller.
        revoked_at: Timestamp of revocation. Null while active.
        revoked_by: ULID of the user who performed the revocation.
        revoked_reason: Mandatory reason supplied at revocation time.
    """

    token: str
    revoked_at: datetime | None = None
    revoked_by: str | None = None
    revoked_reason: str | None = None

    @property
    def status(self) -> CertificateStatus:
        """Compute the current certificate lifecycle status.

        Returns:
            CertificateStatus: REVOKED, EXPIRED, or ACTIVE.
        """
        if self.revoked_at is not None:
            return CertificateStatus.REVOKED
        if self.expires_at is not None and datetime.now(UTC) > self.expires_at:
            return CertificateStatus.EXPIRED
        return CertificateStatus.ACTIVE

    @property
    def is_revokable(self) -> bool:
        """Check whether the certificate can be revoked.

        Returns:
            bool: True only if the certificate is currently active.
        """
        return self.status == CertificateStatus.ACTIVE
